project_id = "wizljmliujeuvamnkibo"

[functions.generate-practice-questions]
verify_jwt = false

[functions.ai-mentor-chat]
verify_jwt = false

[functions.generate-mcq-questions]
verify_jwt = false

[functions.seed-mcq-questions]
verify_jwt = false

[functions.get-random-mcq-questions]
verify_jwt = false
